name: mrz_scanner
description: A package that allows you to Scan any kind of documents that have
  any mrz format
version: 0.0.1+3
homepage: https://github.com/F-BONAPARTA/mrz_scanner

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  camera: ^0.11.0
  camera_platform_interface: ^2.2.2
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1
  google_mlkit_text_recognition: ^0.13.0
  mrz_parser: ^2.0.0
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null
